
package com.andy.bana_mboka.model;

/**
 *
 * @author admin
 */
public enum CatService {
   VAGENT,BAGAGISTE,DOMESTIQUE,COIFFEUR,CAISSIER,CAMERISTE,COMISSAIRE,COMMISSIONAIRE,CONCIERGE,COURSIER,DETECTIVE,ECRIVAIN,EDUCATEUR,ESCORT,FEMME_DE_MENAGE, GARDE_DU_CORP,HOMME_A_TOUT_FAIRE,LAVEUR,MESSAGER,ORGANISATEUR_DE_MARIAGE,PISTEUR,SECOURISTE,PLEUREUSE,POLICIER,POMPIER,PROMENEUR_DE_CHIEN,REDACTEUR,SECRETARIAT,TECHNICIEN,TELECONSEILLER,TOILETTEUR,MANAGEUR, VIDEUR;
}
