
package com.andy.bana_mboka.model;

/**
 *
 * @author admin
 */
public enum Secteur {
  AGRO_ALIMENTAIRE,BANQUE,ASSURANCE,BOIS,BATIMENTS,MATERIAUX_DE_CONSTRUCTION,CHIMIE,COMMERCE,DISTRIBUTION,EDITION,COMMUNICATION,MULTIMEDIA,ELECTRONIQUE,ETUDES,CONSEILS,INDUSTRIES,INFORMATIQUES,TELECOMS,MACHINES,EQUIPEMENTS,METALLURGIE,PLASTIQUE,SERVICES,TEXTILES,HABILLEMENT,CHAUSSURE,TRANSPORT,LOGISTIQUE;  
}
